// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/products/new": {
    params: {};
  };
  "/products/:id/edit": {
    params: {
      "id": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/products/new" | "/products/:id/edit";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/products.new.tsx": {
    id: "routes/products.new";
    page: "/products/new";
  };
  "routes/products.edit.tsx": {
    id: "routes/products.edit";
    page: "/products/:id/edit";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "routes/products.new": typeof import("./app/routes/products.new.tsx");
  "routes/products.edit": typeof import("./app/routes/products.edit.tsx");
};